// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/algorithm/fizzbuzz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Run classic FizzBuzz algorithm on the interval 1-100",
                "responses": {}
            }
        },
        "/algorithm/intervals": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Run the algorithm to get intervals, receiving includes and excludes arrays",
                "parameters": [
                    {
                        "description": "{ includes: [[10, 100],[200, 300],[400, 500]], excludes: [[95, 205],[410, 420]]}",
                        "name": "intervals",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.intervalsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "main.intervalsRequest": {
            "type": "object",
            "properties": {
                "excludes": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "includes": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Solutions Architect Programming Challenge",
	Description:      "API containing the two challenges pertaining to the SA programming challenge",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
