definitions:
  main.intervalsRequest:
    properties:
      excludes:
        items:
          items:
            type: integer
          type: array
        type: array
      includes:
        items:
          items:
            type: integer
          type: array
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: API containing the two challenges pertaining to the SA programming
    challenge
  title: Solutions Architect Programming Challenge
  version: "1.0"
paths:
  /algorithm/fizzbuzz:
    get:
      produces:
      - application/json
      responses: {}
      summary: Run classic FizzBuzz algorithm on the interval 1-100
  /algorithm/intervals:
    post:
      consumes:
      - application/json
      parameters:
      - description: '{ includes: [[10, 100],[200, 300],[400, 500]], excludes: [[95,
          205],[410, 420]]}'
        in: body
        name: intervals
        required: true
        schema:
          $ref: '#/definitions/main.intervalsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Run the algorithm to get intervals, receiving includes and excludes
        arrays
swagger: "2.0"
